services:      # Déclaration des conteneurs à déployer

  proxy:    # Conteneur de proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task4
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end

  front-end:    # Deuxième conteneur
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    depends_on:
      - back-end          # Ce service démarre après service1

  back-end:    # Premier conteneur
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4  # Nom de l'image Docker construite
